name = "helvior-ping-by-git"
main = "src/index.js"
compatibility_date = "2025-07-27"
workers_dev = true

[triggers]
crons = ["*/10 * * * *"]

[vars]
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1399077097657471076/Ca5OhWO6L2GkcLqUI11sRSEA7lC-ACz6HlWHsiuc3iWU-PyKddkO9XX2TIRBJcmSxEHZ"

[observability.logs]
enabled = true