name: Keep RenderServer Helvior Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Chạy mỗi 10 phút
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping endpoints
        id: ping
        run: |
          set +e  # Cho phép lệnh fail nhưng script vẫn tiếp tục
          
          urls=(
            "https://helvior.io.vn/"
            "https://helvior-server.onrender.com/"
          )

          now=$(TZ='Asia/Ho_Chi_Minh' date '+%H:%M:%S - %d/%m/%Y')
          embed_description=""
          overall_status="success"

          for url in "${urls[@]}"; do
            echo "--> Đang ping: $url"
            status=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$url")
            if [[ "$status" == "200" ]]; then
              emoji="✅"; statusText="Thành công"
            else
              emoji="❌"; statusText="Thất bại"
              overall_status="fail"
            fi
            embed_description+=$(printf "%s **%-45s** → %s (%s)\\n" "$emoji" "$url" "$statusText" "$now")
          done

          echo "status=$overall_status" >> $GITHUB_OUTPUT
          echo "description<<EOF" >> $GITHUB_OUTPUT
          echo "$embed_description" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Discord webhook (Embed)
        if: always()  # Luôn gửi dù pass hay fail
        run: |
          webhook="https://discord.com/api/webhooks/1398977090942144614/LKCSO37xoWiyTYK232I8qWe2JFxWb85u2DkLvCK8yK3LzWiXfa8xHgET9R3PE8xcK7x_"
          description="${{ steps.ping.outputs.description }}"
          status="${{ steps.ping.outputs.status }}"
          now=$(TZ='Asia/Ho_Chi_Minh' date '+%Y-%m-%dT%H:%M:%S%z')

          if [ "$status" = "success" ]; then
            color=3066993   # Màu xanh lá
            title="✅ Tất cả endpoint đều hoạt động"
          else
            color=15158332  # Màu đỏ
            title="❌ Một số endpoint bị lỗi"
          fi

          # Tạo payload JSON với Embed
          json_payload=$(jq -n \
            --arg title "$title" \
            --arg description "$description" \
            --arg now "$now" \
            --argjson color "$color" \
            '{
              embeds: [
                {
                  title: $title,
                  description: $description,
                  color: $color,
                  timestamp: $now
                }
              ]
            }'
          )

          curl -s -X POST -H "Content-Type: application/json" \
            -d "$json_payload" "$webhook"
