name: Keep RenderServer Helvior Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Chạy mỗi 10 phút
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Helvior Services
        run: |
          echo "\n==> Bắt đầu kiểm tra hai endpoint..."

          urls=(
            "https://helvior.io.vn/"
            "https://helvior-server.onrender.com/"
          )

          webhook="https://discord.com/api/webhooks/1398977090942144614/LKCSO37xoWiyTYK232I8qWe2JFxWb85u2DkLvCK8yK3LzWiXfa8xHgET9R3PE8xcK7x_"

          now=$(TZ='Asia/Ho_Chi_Minh' date '+%H:%M:%S - %d/%m/%Y')
          message=""

          for url in "${urls[@]}"; do
            echo "\n--> Đang ping: $url"
            status=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$url")

            if [[ "$status" == "200" ]]; then
              statusText="Thành công"
              emoji="✅"
            else
              statusText="Thất bại "
              emoji="❌"
            fi

            # Căn URL trái 45 ký tự, dùng <> để ngăn preview, suppress embed
            formatted=$(printf "%s Ping %-45s => %s (%s)." "$emoji" "<$url>" "$statusText" "$now")
            message+="$formatted\n"
          done

          message+="---------------------------------------------------------------------"

          echo -e "$message"

          curl -s -X POST -H 'Content-type: application/json' \
            --data "{\"content\": \"$message\", \"flags\": 4096}" "$webhook"
